#!/bin/bash
hg clone https://Drakeo@bitbucket.org/NickyD/autobuild-1.0


hg clone https://bitbucket.org/NickyD/3p-google-breakpad

hg clone https://bitbucket.org/NickyD/3p-ndphysicsstub

hg clone https://bitbucket.org/NickyD/jsoncpp

hg clone https://bitbucket.org/NickyD/3p-glod

hg clone https://bitbucket.org/NickyD/3p-xmlrpc-epi

hg clone  https://bitbucket.org/NickyD/3p-jsoncpp

wget -c https://bitbucket.org/Drakeo/firestorm-testing-boost/downloads/boost-FS-USL-157.tar.gz

hg clone https://bitbucket.org/Drakeo/3p-colladadom-usl

hg clone https://bitbucket.org/tonyasouther/llqtwebkit-64

wget -c http://slackbuilds.org/slackbuilds/14.1/libraries/c-ares.tar.gz

wget  -c http://c-ares.haxx.se/download/c-ares-1.10.0.tar.gz

wget -c https://bitbucket.org/Drakeo/firestorm-testing-boost/downloads/hunspell-USL.tar.gz

hg clone https://bitbucket.org/Drakeo/3p-libndofdev-linux64

hg clone https://bitbucket.org/lindenlab/3p-glh-linear

wget -c  https://bitbucket.org/Drakeo/firestorm-testing-boost/downloads/tut-common-noarch-USL.tgz

hg clone https://bitbucket.org/Drakeo/3p-uriparser-64-usl

wget -c https://bitbucket.org/Drakeo/firestorm-testing-boost/downloads/tut-common-noarch-USL.tgz

wget -c http://slackbuilds.org/slackbuilds/14.1/libraries/pangox-compat.tar.gz

wget -c http://slackbuilds.org/slackbuilds/14.1/libraries/libminizip.tar.gz

wget -c https://bitbucket.org/Drakeo/firestorm-testing-boost/downloads/fmodstudio-1.0.6-x86_64-slw-14.1-USL-1_DKo.tgz

wget -c http://slackbuilds.org/slackbuilds/14.1/libraries/OpenAL.tar.gz

wget -c http://slackbuilds.org/slackbuilds/14.1/libraries/freealut.tar.gz

